from typing import Protocol
from system_test.core.drivers.commons.result import Result
from system_test.core.drivers.system.commons.dtos.car_request import AddCarRequest, UpdateCarRequest
from system_test.core.drivers.system.commons.dtos.car_response import AddCarResponse
from system_test.core.drivers.system.commons.dtos.auth_request import LoginRequest
from system_test.core.drivers.system.commons.dtos.auth_response import LoginResponse
from system_test.core.drivers.system.commons.dtos.reservation_request import CreateReservationRequest
from system_test.core.drivers.system.commons.dtos.reservation_response import (
    ReservationResponse,
)


class SystemDriver(Protocol):
    def go_to_system(self) -> Result[None]: ...

    def login(self, request: LoginRequest) -> Result[LoginResponse]: ...

    def add_car(self, request: AddCarRequest) -> Result[AddCarResponse]: ...

    def update_car(self, car_id: str, request: UpdateCarRequest) -> Result[None]: ...

    def delete_car(self, car_id: str) -> Result[None]: ...

    def list_cars(self) -> Result[list[AddCarResponse]]: ...

    def get_car(self, car_id: str) -> Result[AddCarResponse]: ...

    def create_reservation(self, request: CreateReservationRequest) -> Result[ReservationResponse]: ...

    def list_reservations(self) -> Result[list[ReservationResponse]]: ...

    def get_reservation(self, reservation_id: int) -> Result[ReservationResponse]: ...

    def close(self) -> None: ...
