from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from system_test.core.scenario.port.given.given_stage import GivenStage


class GivenCar(Protocol):
    """Port for fluent car setup during given stage."""

    def with_name(self, value: str) -> GivenCar: ...

    def with_connector_types(self, value: list) -> GivenCar: ...

    def with_battery_charge_limit(self, value: int) -> GivenCar: ...

    def with_battery_size(self, value: int) -> GivenCar: ...

    def with_max_kw_ac(self, value: int) -> GivenCar: ...

    def with_max_kw_dc(self, value: int) -> GivenCar: ...

    def exists(self) -> GivenStage: ...
