from typing import Protocol

from system_test.core.scenario.port.when.steps.when_step import WhenStep


class WhenCreateReservation(WhenStep[object, object], Protocol):
    def reservation_id(self, alias: str) -> WhenCreateReservation: ...

    def car_id(self, alias: str) -> WhenCreateReservation: ...

    def charging_point_id(self, value: str) -> WhenCreateReservation: ...

    def start_time(self, value: str) -> WhenCreateReservation: ...

    def end_time(self, value: str) -> WhenCreateReservation: ...
