from typing import Protocol

from system_test.core.scenario.port.when.steps.when_step import WhenStep


class WhenUpdateCar(WhenStep[object, object], Protocol):
    def car_id(self, alias: str) -> WhenUpdateCar: ...

    def with_name(self, value: str) -> WhenUpdateCar: ...

    def with_connector_types(self, value: list) -> WhenUpdateCar: ...

    def with_battery_charge_limit(self, value: int) -> WhenUpdateCar: ...

    def with_battery_size(self, value: int) -> WhenUpdateCar: ...

    def with_max_kw_ac(self, value: int) -> WhenUpdateCar: ...

    def with_max_kw_dc(self, value: int) -> WhenUpdateCar: ...
